import "./globals.css";
import { Inter } from "next/font/google";
import Header from '@/components/header'
import Sidebar from '@/components/sidebar'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const headerHeight = "40px";

  return (
    <html lang="n">
      <body className={inter.className}>
        <div className="flex flex-col h-screen">
          <Header />
          <div className="flex flex-row w-full h-full">
            <Sidebar />
            <div className="w-full h-full">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
